// Movie categories - matching the web app
export const categories = [
  { _id: "hanh-dong", name: "Hành Động", slug: "hanh-dong" },
  { _id: "co-trang", name: "Cổ Trang", slug: "co-trang" },
  { _id: "kinh-di", name: "Kinh Dị", slug: "kinh-di" },
  { _id: "tinh-cam", name: "Tình Cảm", slug: "tinh-cam" },
  { _id: "tam-ly", name: "Tâm Lý", slug: "tam-ly" },
  { _id: "hai-huoc", name: "Hài Hước", slug: "hai-huoc" },
  { _id: "hinh-su", name: "Hình Sự", slug: "hinh-su" },
  { _id: "chien-tranh", name: "Chiến Tranh", slug: "chien-tranh" },
  { _id: "tai-lieu", name: "Tài Liệu", slug: "tai-lieu" },
  { _id: "bi-an", name: "Bí Ẩn", slug: "bi-an" },
  { _id: "phim-18", name: "Phim 18+", slug: "phim-18" },
  { _id: "than-thoai", name: "Thần Thoại", slug: "than-thoai" },
  { _id: "the-thao", name: "Thể Thao", slug: "the-thao" },
  { _id: "am-nhac", name: "Âm Nhạc", slug: "am-nhac" },
  { _id: "gia-dinh", name: "Gia Đình", slug: "gia-dinh" },
  { _id: "hoc-duong", name: "Học Đường", slug: "hoc-duong" },
  { _id: "phieu-luu", name: "Phiêu Lưu", slug: "phieu-luu" },
  { _id: "khoa-hoc", name: "Khoa Học", slug: "khoa-hoc" },
  { _id: "vien-tuong", name: "Viễn Tưởng", slug: "vien-tuong" },
  { _id: "kinh-dien", name: "Kinh Điển", slug: "kinh-dien" },
  { _id: "hoat-hinh", name: "Hoạt Hình", slug: "hoat-hinh" },
  { _id: "chinh-kich", name: "Chính Kịch", slug: "chinh-kich" },
  { _id: "gay-can", name: "Gay Cấn", slug: "gay-can" },
  { _id: "drama", name: "Drama", slug: "drama" },
];

export const countries = [
  { _id: "viet-nam", name: "Việt Nam", slug: "viet-nam" },
  { _id: "trung-quoc", name: "Trung Quốc", slug: "trung-quoc" },
  { _id: "han-quoc", name: "Hàn Quốc", slug: "han-quoc" },
  { _id: "nhat-ban", name: "Nhật Bản", slug: "nhat-ban" },
  { _id: "thai-lan", name: "Thái Lan", slug: "thai-lan" },
  { _id: "au-my", name: "Âu Mỹ", slug: "au-my" },
  { _id: "dai-loan", name: "Đài Loan", slug: "dai-loan" },
  { _id: "hong-kong", name: "Hồng Kông", slug: "hong-kong" },
  { _id: "an-do", name: "Ấn Độ", slug: "an-do" },
  { _id: "anh", name: "Anh", slug: "anh" },
  { _id: "phap", name: "Pháp", slug: "phap" },
  { _id: "canada", name: "Canada", slug: "canada" },
  { _id: "duc", name: "Đức", slug: "duc" },
  { _id: "tay-ban-nha", name: "Tây Ban Nha", slug: "tay-ban-nha" },
  { _id: "tho-nhi-ky", name: "Thổ Nhĩ Kỳ", slug: "tho-nhi-ky" },
  { _id: "brazil", name: "Brazil", slug: "brazil" },
  { _id: "philippines", name: "Philippines", slug: "philippines" },
  { _id: "bo-dao-nha", name: "Bo Đào Nha", slug: "bo-dao-nha" },
  { _id: "y", name: "Ý", slug: "y" },
  { _id: "ba-lan", name: "Ba Lan", slug: "ba-lan" },
  { _id: "uc", name: "Úc", slug: "uc" },
  { _id: "indonesia", name: "Indonesia", slug: "indonesia" },
  { _id: "mexico", name: "Mexico", slug: "mexico" },
  { _id: "thuy-dien", name: "Thụy Điển", slug: "thuy-dien" },
  { _id: "malaysia", name: "Malaysia", slug: "malaysia" },
  { _id: "nga", name: "Nga", slug: "nga" },
  { _id: "ha-lan", name: "Hà Lan", slug: "ha-lan" },
  { _id: "na-uy", name: "Na Uy", slug: "na-uy" },
  { _id: "dan-mach", name: "Đan Mạch", slug: "dan-mach" },
  { _id: "bi", name: "Bỉ", slug: "bi" },
  { _id: "nam-phi", name: "Nam Phi", slug: "nam-phi" },
  { _id: "ai-len", name: "Ai-len", slug: "ai-len" },
  { _id: "colombia", name: "Colombia", slug: "colombia" },
  { _id: "argentina", name: "Argentina", slug: "argentina" },
  { _id: "quoc-gia-khac", name: "Quốc Gia Khác", slug: "quoc-gia-khac" },
];

// Gradient colors for category cards
export const CATEGORY_GRADIENTS = [
  ['#667eea', '#764ba2'],
  ['#f093fb', '#f5576c'],
  ['#4facfe', '#00f2fe'],
  ['#43e97b', '#38f9d7'],
  ['#fa709a', '#fee140'],
  ['#a18cd1', '#fbc2eb'],
  ['#ffecd2', '#fcb69f'],
];
